  drop table if exists audit_trail CASCADE;

    drop table if exists investor_details CASCADE;

    drop table if exists product CASCADE;

    drop table if exists withdrawal CASCADE;

    create table audit_trail (
       id bigint generated by default as identity,
        event varchar(255) not null,
        status varchar(255) not null,
        timestamp timestamp not null,
        withdrawal_id bigint not null,
        primary key (id)
    );

    create table investor_details (
       id bigint generated by default as identity,
        address varchar(255) not null,
        date_of_birth date not null,
        email_address varchar(255) not null,
        mobile_number varchar(255) not null,
        name varchar(255) not null,
        surname varchar(255) not null,
        primary key (id)
    );

    create table product (
       id bigint generated by default as identity,
        balance double,
        name varchar(255) not null,
        type varchar(255) not null,
        investor_details_id bigint not null,
        primary key (id)
    );

    create table withdrawal (
       id bigint generated by default as identity,
        amount double,
        status varchar(255),
        investor_details_id bigint not null,
        primary key (id)
    );

    alter table audit_trail
       add constraint FKja9n3db65dg6ow622vsejm4eh
       foreign key (withdrawal_id)
       references withdrawal;

    alter table product
       add constraint FKrd4ellg0opcerq09fn68scgdg
       foreign key (investor_details_id)
       references investor_details;

    alter table withdrawal
       add constraint FKhn16ynpauk5vralb7rcyp0r1h
       foreign key (investor_details_id)
       references investor_details;


    INSERT INTO investor_details VALUES(1, 'address test', '1870-01-01', 'investor@mom.co.za', '0983273733', 'investor',' investorSurname');


    INSERT INTO product VALUES(1, 36000, 'FLEX','SAVINGS', 1);
    INSERT INTO product VALUES(2, 500000, 'AR','RETIREMENT', 1);